apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
  labels:
    service: reverse-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: reverse-proxy
  template:
    metadata:
      labels:
        service: reverse-proxy
    spec:
      containers:
      - name: reverse-proxy
        image: gonzaga626/05-reverse-proxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m" 
        ports:
        - containerPort: 8080
